// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTP16Njk3_It0f6MaUGNRwgKai72XodYY',
    appId: '1:456761030249:web:6fe3509997b3b5a0ff94f8',
    messagingSenderId: '456761030249',
    projectId: 'campusmeals-37097',
    authDomain: 'campusmeals-37097.firebaseapp.com',
    storageBucket: 'campusmeals-37097.appspot.com',
    measurementId: 'G-D3FL2ZJ7KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSTyz1UhkSxLaFjNVvPGnEps4pi_WpOA',
    appId: '1:456761030249:android:197871f4344cc75dff94f8',
    messagingSenderId: '456761030249',
    projectId: 'campusmeals-37097',
    storageBucket: 'campusmeals-37097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdpOo6ubHO-KoVwn_l2zqt7OIlLcz2gTA',
    appId: '1:456761030249:ios:10de2462f9c28cd8ff94f8',
    messagingSenderId: '456761030249',
    projectId: 'campusmeals-37097',
    storageBucket: 'campusmeals-37097.appspot.com',
    iosBundleId: 'com.example.campusMeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdpOo6ubHO-KoVwn_l2zqt7OIlLcz2gTA',
    appId: '1:456761030249:ios:10de2462f9c28cd8ff94f8',
    messagingSenderId: '456761030249',
    projectId: 'campusmeals-37097',
    storageBucket: 'campusmeals-37097.appspot.com',
    iosBundleId: 'com.example.campusMeals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTP16Njk3_It0f6MaUGNRwgKai72XodYY',
    appId: '1:456761030249:web:6920509bd05aa152ff94f8',
    messagingSenderId: '456761030249',
    projectId: 'campusmeals-37097',
    authDomain: 'campusmeals-37097.firebaseapp.com',
    storageBucket: 'campusmeals-37097.appspot.com',
    measurementId: 'G-N4RPZ9KYB9',
  );
}
